[package]
name = "smt-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
smt-core = { path = "../smt-core" }
smt-solver = { path = "../smt-solver" }
smt-parser = { path = "../smt-parser" }
smt-api = { path = "../smt-api" }
smt-mba = { path = "../smt-mba" }
